### ISSUE TITLE
model parameter initialization and backbone problems

### ISSUE THREAD

**Issue by fengjk12138** [TANGHAIHAN/TAFNet#1]
Are your backbone models parameter initialized with Imagenet pretrained?
And, in your paper, you say , "we use three VGG16 [2] networks as the backbone", "We used BL [7] as the backbone and built our structure based on [3]".
I find BL is implemented with vgg19. So which model you use in paper?

**Comment by TANGHAIHAN** [comment]
vgg16, and initialized with Imagenet pretrained.

**Comment by fengjk12138** [comment]
o, thanks
